services:
  valkey:
    image: valkey/valkey:7.2
    container_name: valkey
    restart: always
    ports:
      - '6379:6379'
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:valkey:6379
    ports:
      - "8081:8081"
